class AppImages {
  AppImages._();
  static String actions = 'assets/images/Actions.png';
  static String home = 'assets/images/Home.png';
  static String calender = 'assets/images/Calendar.png';
  static String community = 'assets/images/Community.png';
  static String profile = 'assets/images/Profile.png';
  static String chatOutline = 'assets/images/Chat-Outline.png';
  static String notification = 'assets/images/Notification.png';
  static String caution = 'assets/images/caution.png';
  static String arrow = 'assets/images/arrow.png';
  static String communityColoured = 'assets/images/Community_colored.png';
  static String homeColoured = 'assets/images/Home_colored.png';
  static String headset = 'assets/images/headset.png';
  static String openbook = 'assets/images/openbook.png';
  static String sethoscope = 'assets/images/sethoscope.png';
  static String letterbox = 'assets/images/letterbox.png';
  static String person = 'assets/images/person.png';
  static String useofdrug = 'assets/images/useofdrug.png';
  static String useofdrug1 = 'assets/images/useofdrug1.png';
  static String useofdrug2 = 'assets/images/useofdrug2.png';
  static String theraphy = 'assets/images/theraphy.png';
  static String search = 'assets/images/search.png';
  static String image1 = 'assets/images/image1.png';
  static String image3 = 'assets/images/image3.png';
  static String image2 = 'assets/images/image2.png';
  static String image4 = 'assets/images/image4.png';
  static String share = 'assets/images/share.png';
  static String bookmark = 'assets/images/bookmark.png';
  static String dropdown = 'assets/images/dropdown.png';
  static String link = 'assets/images/link.png';
  static String speaker = 'assets/images/Speaker.png';
  static String backward = 'assets/images/backward.png';
  static String foward = 'assets/images/foward.png';
  static String st = 'assets/images/st.png';
}
